
import java.awt.Graphics;
import java.awt.Color;
import matopeli.*;

public class MatopeliGUI extends javax.swing.JFrame{

    Graphics db;
    Thread paivittaja = null;
    Logiikka peli = new Logiikka();

    /**
     * Creates new form NewJFrame
     */
    public MatopeliGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scoreLabel = new javax.swing.JLabel();
        Kentta = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel.setText("score: 000");
        scoreLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Kentta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KenttaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout KenttaLayout = new javax.swing.GroupLayout(Kentta);
        Kentta.setLayout(KenttaLayout);
        KenttaLayout.setHorizontalGroup(
            KenttaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );
        KenttaLayout.setVerticalGroup(
            KenttaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(Kentta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Kentta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KenttaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KenttaKeyPressed
        // TODO add your handling code here:
                int nappain = evt.getKeyCode();

        if (paivittaja == null) {
            paivittaja = new Thread();
            paivittaja.start();
        }

        if (nappain == 38) {  // ylänuoli
            peli.asetaSuunta("ylös");
            System.out.println("ylös");
        }
        if (nappain == 40) {  // alanuoli
            peli.asetaSuunta("alas");
        }
        if (nappain == 37) { // vasennuoli
            peli.asetaSuunta("vasemmalle");
        }
        if (nappain == 39) { // oikeanuoli
            peli.asetaSuunta("oikealle");
        }

    }//GEN-LAST:event_KenttaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatopeliGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatopeliGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatopeliGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatopeliGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MatopeliGUI().setVisible(true);

            }
        });
        
    }

    public void KenttaPaint(Graphics g) {
        super.paint(g);

        int[][] alue = peli.getKentta();
        
        int x=0;
        int y=0;

        for (int i = 0; i < alue.length; i++) {
            
            for (int j = 0; j < alue[i].length; j++) {
                
                g.setColor(Color.BLACK);
                g.drawRect(x, y, 5, 5);
                x = x + 5;
            }
            y = y + 5;
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Kentta;
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables
}
