/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lammenoj
 */
import java.awt.Graphics;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import matopeli.*;

public class matopeliGUI2 extends javax.swing.JFrame {

    private class Kuuntelija implements ActionListener {

        public Kuuntelija() {

        }

        @Override
        public void actionPerformed(ActionEvent ae) {
            peli.etene();
            repaint();
        }
    }
    /**
     * Creates new form matopeliGUI2
     */
    Graphics db;
    Thread paivittaja = null;
    Logiikka peli = new Logiikka();
    Timer kello;

    public matopeliGUI2() {
        initComponents();
        kello = new Timer(100, new Kuuntelija());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        int nappain = evt.getKeyCode();

        System.out.println(nappain);

        if (nappain == 38) {  // ylänuoli
            peli.asetaSuunta("ylös");
        }
        if (nappain == 40) {  // alanuoli
            peli.asetaSuunta("alas");
        }
        if (nappain == 37) { // vasennuoli
            peli.asetaSuunta("vasemmalle");
        }
        if (nappain == 39) { // oikeanuoli
            peli.asetaSuunta("oikealle");
        }
        if (nappain == 32) { // Space
            kello.start();
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matopeliGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matopeliGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matopeliGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matopeliGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new matopeliGUI2().setVisible(true);
            }
        });

    }

    public void Kenttapaint(Graphics g) {

        super.paint(g);

        int[][] alue = peli.getKentta();

        int x;
        int y = 30;

        for (int i = 0; i < alue.length; i++) {
            x = 10;
            for (int j = 0; j < alue[i].length; j++) {

                g.setColor(Color.WHITE);

                if (alue[i][j] == 3) {
                    g.setColor(Color.RED);
                } else if (alue[i][j] == 1) {
                    g.setColor(Color.BLACK);
                } else if (alue[i][j] == 2) {
                    g.setColor(Color.PINK);
                }
                g.fillRect(x, y, 10, 10);

                x = x + 10;
            }
            y = y + 10;
        }
    }

    public void paint(Graphics g) {

        super.paint(g);

        int[][] alue = peli.getKentta();

        int x;
        int y = 30;

        for (int i = 0; i < alue.length; i++) {
            x = 10;
            for (int j = 0; j < alue[i].length; j++) {

                if (alue[i][j] == 3) {
                    g.setColor(Color.RED);
                    g.fillRect(x, y, 10, 10);
                } else if (alue[i][j] == 2) {
                    g.setColor(Color.PINK);
                    g.fillRect(x, y, 10, 10);
                }
                x = x + 11;
            }
            y = y + 11;
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
